packages:
  - playground
  - examples/*

catalogs:
  build:
    '@jridgewell/remapping': ^2.3.5
    bumpp: ^9.11.1
    esno: ^4.8.0
    nodemon: ^3.1.10
    rollup: ^4.52.5
    typescript: ^5.9.3

    webpack: ^5.102.1
  eslint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    eslint-plugin-antfu: ^3.1.1
    eslint-vitest-rule-tester: ^2.3.0
    svelte-eslint-parser: ^1.4.0

  nuxt:
    '@nuxt/kit': ^3.20.0
    '@nuxt/schema': ^3.20.0

  types:
    '@types/node': ^20.11.5
  utils:
    chalk: ^5.6.2
    fast-glob: ^3.3.3
    magic-string: ^0.30.21
    rimraf: ^6.1.0

    unplugin: ^2.3.10
  vite:
    vite: ^6.4.1
    vite-plugin-inspect: ^11.3.3

    vitest: ^4.0.7
