packages:
  - playground
  - examples/*

catalogs:
  build:
    '@jridgewell/remapping': ^2.3.5
    bumpp: ^9.3.0
    esno: ^4.0.0
    nodemon: ^3.0.3
    rollup: ^4.9.5
    tsup: ^8.0.1
    typescript: ^5.3.3

    webpack: ^5.89.0
  eslint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.34.0
    eslint-plugin-antfu: ^3.1.1
    eslint-vitest-rule-tester: ^2.2.1
    svelte-eslint-parser: ^1.3.1

  nuxt:
    '@nuxt/kit': ^3.9.3
    '@nuxt/schema': ^3.9.3

  types:
    '@types/node': ^20.11.5
  utils:
    chalk: ^5.3.0
    fast-glob: ^3.3.2
    magic-string: ^0.30.18
    rimraf: ^5.0.5

    unplugin: ^2.3.9
  vite:
    vite: ^5.0.12
    vite-plugin-inspect: ^0.8.1

    vitest: ^1.2.1
